# Generated by Django 5.0.4 on 2024-05-20 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.BigIntegerField()),
                ('Discount', models.IntegerField()),
                ('Image', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentCategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('AccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='WebApp.accessories')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accessories',
            name='CategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='WebApp.categories'),
        ),
        migrations.CreateModel(
            name='ImportAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalAmount', models.BigIntegerField(default=0)),
                ('ImportDate', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.BigIntegerField()),
                ('AccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='WebApp.accessories')),
                ('ImportAccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='WebApp.importaccessory')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalAmount', models.BigIntegerField()),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=255)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.BigIntegerField()),
                ('AccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='WebApp.accessories')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='WebApp.orders')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='ParentCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='WebApp.parentcategories'),
        ),
    ]
