# Generated by Django 5.0.4 on 2024-05-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='orders',
            name='IsCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='IsPaid',
            field=models.BooleanField(default=False),
        ),
    ]
