# Generated by Django 5.0.4 on 2024-05-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_categories_parentcategories_delete_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='WebApp.categories')),
            ],
        ),
    ]
