# Generated by Django 5.0.4 on 2024-05-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_accessories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
