# Generated by Django 5.0.4 on 2024-05-07 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='AccessoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartAccessory', to='WebApp.accessories'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartUser', to='WebApp.users'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=255)),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderUser', to='WebApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderAccessory', to='WebApp.accessories')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='WebApp.orders')),
            ],
        ),
    ]
