# Generated by Django 5.0.4 on 2024-05-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_alter_cart_accessoryid_alter_cart_userid_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='CategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='WebApp.categories'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='AccessoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='WebApp.accessories'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='WebApp.users'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='ParentCategoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='WebApp.parentcategories'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='AccessoryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='WebApp.accessories'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='WebApp.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='WebApp.users'),
        ),
        migrations.CreateModel(
            name='ImportAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImportDate', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='WebApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='WebApp.accessories')),
                ('ImportAccessoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='WebApp.importaccessory')),
            ],
        ),
    ]
